language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/behat --config ./test/behat/behat.yml
  - phpunit -c ./test/phpunit/phpunit.xml